# BASIC NUMPY
## Getting started
### Import numpy

In [ ]:
import numpy as np

### Checking version

In [ ]:
print(np.__version__)

## Creating arrays
### Create numpy ndarray object (can pass a list or a tuple or any array-like object)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

### Dimensions in array

In [ ]:
# 0 to 3D array respectively
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

### Check number of dimensions

In [ ]:
print(a.ndim)

### Dimension parameter when defining an array

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

## NumPy array indexing
### Access Array Elements

In [ ]:
# 1D array
arr = np.array([1, 2, 3, 4])
print(arr[0])

In [ ]:
# 2D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

In [ ]:
# 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

### Negative Indexing

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

## NumPy array slicing
### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

Note: The result includes the start index, but excludes the end index.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

In [ ]:
# leaving the end parameter blank results in taking from to the end of the array 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

In [ ]:
# similar to this
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

### Negative slicing

In [ ]:
# Note: exclude the last element with -1 index
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

### Step

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
# result: [2 4]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])
# result: [1 3 5 7]

### Slicing 2-D Arrays

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
# result: [7 8 9]

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])
# result: [3 8]

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])
# result: [[2 3 4], [7 8 9]]

## NumPy Data Types
### Data Types in Python
- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
### Data Types in NumPy
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )
### Checking the Data Type of an Array

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
# result: int64

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
# result: <U6
# Unicode character with maximum of 6 characters, stored little endian first

### Creating Arrays With a Defined Data Type

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)
# 4 stands for the number of bytes defined by user

### What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [ ]:
arr = np.array(['a', '2', '3'], dtype='i')

### Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method. 

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)
# result: 
# [1 2 3]
# int32

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)
# result: 
# [1 2 3]
# int64

In [ ]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)
# result:
# [ True False True]
# bool

## NumPy Array Copy vs View
### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
### Copy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

### View

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

In [ ]:
# make changes in the view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

## NumPy Array Shape & Reshape
### Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

### Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape from 1D to 2D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

### Reshape from 1D to 3D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

### Can we reshape into any shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements (raise an error).

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

### Return copy or view 

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)
# result: a view

### Unknown dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

### Flattening the array
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

## NumPy Joining & Splitting
### Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

This command works basing on the dimension of the array, if the array is 1D, concatenate simply lengthen the array. If the there are more dimensions, it axis parameter will be used to determine which dimension should be stacked.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)
# result: [1 2 3 4 5 6]
# similar result as hstack

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
# result:
# [[1 2 5 6]
#  [3 4 7 8]]
# adding axis = 1 will stack along the row

### Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)
# result:
#[[1 4]
# [2 5]
# [3 6]]

### Stacking Along Rows

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)
# result: [1 2 3 4 5 6]

### Stacking Along Columns

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)
# result:
#[[1 2 3]
# [4 5 6]]

### Stacking Along Depths

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)
# result:
#[[[1 4]
# [2 5]
# [3 6]]]

### Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

If the array has less elements than required, it will adjust from the end accordingly.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
# result: [array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)
# result: [array([1, 2]), array([3, 4]), array([5]), array([6])]

### Split Into Arrays 
The return value of the array_split() method is a list containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

### Splitting 2D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
# result:
#[array([[1, 2],
#       [3, 4]]), array([[5, 6],
#       [7, 8]]), array([[ 9, 10],
#       [11, 12]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)
# result:
#[array([[1, 2],
#       [3, 4]]), array([[5, 6],
#       [7, 8]]), array([[ 9, 10],
#       [11, 12]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)
# result:
#[array([[ 1],
#       [ 4],
#       [ 7],
#       [10],
#       [13],
#       [16]]), array([[ 2],
#       [ 5],
#       [ 8],
#       [11],
#       [14],
#       [17]]), array([[ 3],
#       [ 6],
#       [ 9],
#       [12],
#       [15],
#       [18]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)
# result:
#[array([[ 1],
#       [ 4],
#       [ 7],
#       [10],
#       [13],
#       [16]]), array([[ 2],
#       [ 5],
#       [ 8],
#       [11],
#       [14],
#       [17]]), array([[ 3],
#       [ 6],
#       [ 9],
#       [12],
#       [15],
#       [18]])]

## NumPy Searching Arrays
### Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
# result: (array([3, 5, 6]),)

In [ ]:
arr = np.array([10, 14, 93, 41, 8, 7])
x = np.where(arr%2 == 1)
print(x)
# result: (array([2, 3, 5]),)

In [ ]:
arr = np.array([10, 14, 93, 41, 8, 7])
x = np.where(arr%2 == 0)
print(x)
# result: (array([0, 1, 4]),)

### Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)
# result: 1

### Search from the right side

In [ ]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)
# result: 2

### Multiple values
The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

In [ ]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)
# result: [1 2 3]

## NumPy Filter Array
### Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)
# result: [41, 43]

### Creating the Filter Array

In [ ]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

### Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

## Simple Arithmetic
You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a where parameter in which we can specify that condition.
### Addition
The add() function sums the content of two arrays, and return the results in a new array.

In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)

print(newarr)
# result: [30 32 34 36 38 40]

### Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)

print(newarr)
# result: [-10 -1 8 17 26 35]

### Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)

print(newarr)
# result: [200 420 660 920 1200 1500]

### Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)

print(newarr)
# result: [3.33333333 4. 3. 5. 25. 1.81818182]

### Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)

print(newarr)
# result: [1000 3200000 729000000 6553600000000 2500 0]

### Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)
print(newarr)
# result: [1 6 3 0 0 27]

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.remainder(arr1, arr2)

print(newarr)
# result: [1 6 3 0 0 27]

### Quotient and Mod
The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)

print(newarr)
# result: (array([3, 2, 3, 5, 25, 1]), array([1, 6, 3, 0, 0, 27]))

### Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [ ]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)
# result: [1 2 1 2 3 4]